export const environment={
  production:true,
  apiHost: "http://localhost:4000",
  apiAuthUrl: "/api/auth",
  apiPublicacionUrl: "/api/publicaciones",
  apiEmpleadosUrl:"/api/empleado",
  apiUserUrl: "/api/usuarios",
  apiRegistroPublicacionUrl: "/nuevaPublicacion",
  apiObtenerPublicacionesActivasUrl: "/listaPublicaciones/activas/",
  apiObtenerPublicacionesCerradasUrl: "/listaPublicaciones/cerradas/",
  apiEliminarPublicacionUrl: "/eliminarPublicacion/",
  apiCategoriasUrl: "/api/categorias/",
  apiModificarPublicacionUrl: "/modificarPublicacion/",
  apiObtenerPublicacionById: "/publicacionById/",
  apiGetUser: "/obtenerUsuario/",
  apiUpdateUser: "/editarUsuario/",
  apiObtenerPublicacionesActivas: "/listaPublicacionesActivas/",
  apiCrearPostulacion: "/postular",
  apiCancelarPostulacion: "/cancelarPostulacion/",
  apiListaPostulacionesPorUsuario: "/listaPostulaciones/",
  apiListaPostulantes: "/listaPostulantes/",
  apiEstadoPostulacionAceptado:"/aceptarPostulacion/"
}
